from typing import Annotated

from langgraph.graph import MessagesState
from typing_extensions import TypedDict


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    asset_type: Annotated[str, "Asset type under analysis such as stock or crypto"]
    instrument_context: Annotated[str, "Deterministic ticker identity resolved at run start"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Sentiment Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]
    # Structured multi-agent debate (opt-in enable_debate): round records,
    # claim ledger, L1 severity verdict, judge scores. Absent when the
    # legacy one-shot chain runs.
    debate_state: Annotated[
        dict, "Structured debate state (rounds, claim ledger, L1, judge)"
    ]
    structured_risk_state: Annotated[
        dict,
        "Structured RISK debate state (rounds, claim ledger, L1, judge) — "
        "direction.md parity; absent on the legacy risk chain",
    ]
    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    pm_decision: Annotated[
        dict | None,
        "Structured PortfolioDecision output (model_dump mode=json) adjacent to "
        "the rendered final_trade_decision text; absent on free-text fallback",
    ]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]
    risk_context: Annotated[dict, "Deterministic risk snapshot (CVaR/stress) precomputed for the Portfolio Manager prompt before the graph runs"]
    computed_decision_context: Annotated[str, "Deterministic Phase A-E advisory context (regime gate / trade plan card / risk snapshot / pre-open rows) injected to the Trader, Portfolio Manager and the 3 risk debators"]
    risk_independent_stances: Annotated[
        dict, "Independent pre-debate risk stances (aggressive/conservative/neutral), no cross-talk"
    ]
    researcher_independent_stances: Annotated[
        dict, "Independent pre-debate researcher stances (bull/bear), no cross-talk"
    ]
    computed_independent_vote: Annotated[
        str, "Deterministic agreement/consensus summary from the independent stances"
    ]
